version: '3'

services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER_NAME}'
      MYSQL_PASSWORD: '${DB_USER_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql_db_data_container:/var/lib/mysql

  app:
    build: 
      dockerfile: Dockerfile
      context: ./server
    command: ["/home/node/app/wait-for-it.sh", "mysql-db:3306", "--", "npm", "start"]
    links:
      - mysql-db
    depends_on:
      - mysql-db
    ports:
      - 3838:3838
    volumes:
      - /home/node/app
      - /home/node/app/node_modules

volumes:
  mysql_db_data_container: